// Autogenerated from Pigeon (v0.1.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class ViaAesReply;
@class ViaAesRequest;

@interface ViaAesReply : NSObject
@property(nonatomic, copy, nullable) NSString * result;
@end

@interface ViaAesRequest : NSObject
@property(nonatomic, copy, nullable) NSString * data;
@property(nonatomic, copy, nullable) NSString * key;
@property(nonatomic, copy, nullable) NSString * iv;
@end

@protocol ViaAesApi
-(nullable ViaAesReply *)encrypt:(ViaAesRequest*)input error:(FlutterError *_Nullable *_Nonnull)error;
-(nullable ViaAesReply *)decrypt:(ViaAesRequest*)input error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void ViaAesApiSetup(id<FlutterBinaryMessenger> binaryMessenger, id<ViaAesApi> _Nullable api);

NS_ASSUME_NONNULL_END
