// Autogenerated from Pigeon (v0.1.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

package com.via.viapigeon;

import io.flutter.plugin.common.BasicMessageChannel;
import io.flutter.plugin.common.BinaryMessenger;
import io.flutter.plugin.common.StandardMessageCodec;
import java.util.ArrayList;
import java.util.HashMap;

/** Generated class from Pigeon. */
@SuppressWarnings("unused")
public class Pigeon {

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class ViaAesReply {
    private String result;
    public String getResult() { return result; }
    public void setResult(String setterArg) { this.result = setterArg; }

    HashMap toMap() {
      HashMap<String, Object> toMapResult = new HashMap<>();
      toMapResult.put("result", result);
      return toMapResult;
    }
    static ViaAesReply fromMap(HashMap map) {
      ViaAesReply fromMapResult = new ViaAesReply();
      Object result = map.get("result");
      fromMapResult.result = (String)result;
      return fromMapResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class ViaAesRequest {
    private String data;
    public String getData() { return data; }
    public void setData(String setterArg) { this.data = setterArg; }

    private String key;
    public String getKey() { return key; }
    public void setKey(String setterArg) { this.key = setterArg; }

    private String iv;
    public String getIv() { return iv; }
    public void setIv(String setterArg) { this.iv = setterArg; }

    HashMap toMap() {
      HashMap<String, Object> toMapResult = new HashMap<>();
      toMapResult.put("data", data);
      toMapResult.put("key", key);
      toMapResult.put("iv", iv);
      return toMapResult;
    }
    static ViaAesRequest fromMap(HashMap map) {
      ViaAesRequest fromMapResult = new ViaAesRequest();
      Object data = map.get("data");
      fromMapResult.data = (String)data;
      Object key = map.get("key");
      fromMapResult.key = (String)key;
      Object iv = map.get("iv");
      fromMapResult.iv = (String)iv;
      return fromMapResult;
    }
  }

  /** Generated interface from Pigeon that represents a handler of messages from Flutter.*/
  public interface ViaAesApi {
    ViaAesReply encrypt(ViaAesRequest arg);
    ViaAesReply decrypt(ViaAesRequest arg);

    /** Sets up an instance of `ViaAesApi` to handle messages through the `binaryMessenger` */
    static void setup(BinaryMessenger binaryMessenger, ViaAesApi api) {
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.ViaAesApi.encrypt", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            HashMap<String, HashMap> wrapped = new HashMap<>();
            try {
              @SuppressWarnings("ConstantConditions")
              ViaAesRequest input = ViaAesRequest.fromMap((HashMap)message);
              ViaAesReply output = api.encrypt(input);
              wrapped.put("result", output.toMap());
            }
            catch (Exception exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.ViaAesApi.decrypt", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            HashMap<String, HashMap> wrapped = new HashMap<>();
            try {
              @SuppressWarnings("ConstantConditions")
              ViaAesRequest input = ViaAesRequest.fromMap((HashMap)message);
              ViaAesReply output = api.decrypt(input);
              wrapped.put("result", output.toMap());
            }
            catch (Exception exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
    }
  }
  private static HashMap wrapError(Exception exception) {
    HashMap<String, Object> errorMap = new HashMap<>();
    errorMap.put("message", exception.toString());
    errorMap.put("code", null);
    errorMap.put("details", null);
    return errorMap;
  }
}
